// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulbaetjbyolftpopvjge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsYmFldGpieW9sZnRwb3B2amdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTI3MTIsImV4cCI6MjA2NTE4ODcxMn0.B7zdDJD_gyeWSigYGUSbZMk2bhitZP6HOLHKF8gUIG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);